// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1JEQzdHPbTAudDBkXbl-Y62couGtH9DM',
    appId: '1:219452254582:web:4c69bf9215861e35ae3257',
    messagingSenderId: '219452254582',
    projectId: 'flutter-saknni-app',
    authDomain: 'flutter-saknni-app.firebaseapp.com',
    storageBucket: 'flutter-saknni-app.firebasestorage.app',
    measurementId: 'G-NFDJ3FY4PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNi1SQphvkJ4O3Xw2aHzJT3JxEqsHom7w',
    appId: '1:219452254582:android:2eba2b5be14c553fae3257',
    messagingSenderId: '219452254582',
    projectId: 'flutter-saknni-app',
    storageBucket: 'flutter-saknni-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl7ScvaYsznB-CDNyq_NjuGbwQRBFLiSc',
    appId: '1:219452254582:ios:a3dc4bfdebce0610ae3257',
    messagingSenderId: '219452254582',
    projectId: 'flutter-saknni-app',
    storageBucket: 'flutter-saknni-app.firebasestorage.app',
    iosBundleId: 'com.example.sakkenyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl7ScvaYsznB-CDNyq_NjuGbwQRBFLiSc',
    appId: '1:219452254582:ios:a3dc4bfdebce0610ae3257',
    messagingSenderId: '219452254582',
    projectId: 'flutter-saknni-app',
    storageBucket: 'flutter-saknni-app.firebasestorage.app',
    iosBundleId: 'com.example.sakkenyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1JEQzdHPbTAudDBkXbl-Y62couGtH9DM',
    appId: '1:219452254582:web:2d86c1cedafc8c59ae3257',
    messagingSenderId: '219452254582',
    projectId: 'flutter-saknni-app',
    authDomain: 'flutter-saknni-app.firebaseapp.com',
    storageBucket: 'flutter-saknni-app.firebasestorage.app',
    measurementId: 'G-RP9B2V5RV6',
  );

}